export class CommonConstant {
  /**
   * 百分百宽度
   */
  static readonly WIDTH_FULL = '100%'
  /**
   * 百分百高度
   */
  static readonly HEIGHT_FULL = '100%'
  /**
   * 开屏广告页面默认展示时间，单位秒
   */
  static readonly ADVERTISING_TIME: number = 3;
  /**
   * 结束时间，单位秒
   */
  static readonly ADVERTISING_END_TIME: number = 0;
  /**
   * 存token值的名称（token)
   */
  static readonly TOKEN_NAME: string = 'token';
  /**
   * 用户首选项实例的名称
   */
  static readonly PREFERENCES_NAME: string = 'preferences';
  /**
   * 存用户信息的本地存储名称
   */
  static readonly USER_INFO: string = 'userInfo';
  /**
   * 登录错误
   */
  static readonly DEFAULT_LOGIN_ERROR: string = '登录错误';
}