export class RouterConstant {
  /**
   * 首页
   */
  static readonly PAGE_INDEX = 'pages/Index'
  /**
   * 登录
   */
  static readonly PAGE_LOGIN = 'pages/LoginPage'
  /**
   * 打卡
   */
  static readonly VIEWS_CLOCK = 'views/Learn/Clock'
  /**
   * 打卡记录
   */
  static readonly VIEWS_CLOCK_RECORD = 'views/Learn/ClockRecord'
  /**
   * 学习目标
   */
  static readonly VIEWS_LEARN_TARGET = 'views/Learn/LearnTarget'
  /**
   * 学习工具
   */
  static readonly VIEWS_LEARN_TOOL = 'views/Learn/LearnTool'
  /**
   * 学习平台内容
   */
  static readonly VIEWS_LEARN_CONTENT = 'views/Learn/LearnContent'
  /**
   * 面试平台内容
   */
  static readonly VIEWS_INTERVIEW_CONTENT = 'views/Learn/InterviewContent'
  /**
   * home页面
   */
  static readonly VIEWS_HOME_HOME = 'views/Home/Home'
  /**
   * 文章详情页面
   */
  static readonly VIEWS_HOME_ARTICLE_INFO = 'views/Home/ArticleInfo'
  /**
   * home搜索页面
   */
  static readonly VIEWS_HOME_SEARCH = 'views/Home/Search'
  /**
   * 消息列表页面
   */
  static readonly VIEWS_MESSAGE_LIST = 'views/Message/MessageList'
  /**
   * 个人信息
   */
  static readonly VIEWS_MINE_INFO = 'views/Mine/MineInfo'
  /**
   * 我的收藏
   */
  static readonly VIEWS_MINE_COLLECT = 'views/Mine/MineCollect'
  /**
   * 我的点赞
   */
  static readonly VIEWS_MINE_LIKE = 'views/Mine/MineLike'
  /**
   * 关于我们
   */
  static readonly VIEWS_MINE_ABOUT_US = 'views/Mine/AboutUS'
  /**
   * 设置
   */
  static readonly VIEWS_MINE_SET_UP = 'views/Mine/SetUp'
  /**
   * 隐私政策
   */
  static readonly PAGE_PRIVACY_POLICY = 'pages/PrivacyPolicyPage'
  /**
   * 用户协议
   */
  static readonly PAGE_USER_POLICY = 'pages/UserPolicyPage'
}